---

- hosts:                   all
  remote_user:             pi
  become:                  yes


  tasks:

#    - name:                test connection
#      ping:

    - name:                turn off dhcpcd
      service:
        name:              "dhcpcd"
        state:             "stopped"
        enabled:           "no"

    ###########################################################################################
    ##  Configure root's account ##############################################################
    ###########################################################################################
    - name:                Make sure ~root/.ssh exists
      file:
        name:              "/root/.ssh"
        mode:              "0700"
        owner:             "root"
        group:             "root"
        state:             "directory"

    - name:                root's ssh keys
      copy:
        src:               "/home/jlowther/hadoop/root-ssh/{{ item.src}}"
        dest:              "/root/.ssh/"
        mode:              "{{ item.mode }}"
        owner:             "root"
        group:             "root"
      loop:
        -                  { src:   "authorized_keys",
                             mode:  "0600" }
        -                  { src:   "config",
                             mode:  "0600" }
        -                  { src:   "id_ecdsa",
                             mode:  "0600" }
        -                  { src:   "id_ecdsa.pub",
                             mode:  "0644" }
        -                  { src:   "id_ed25519",
                             mode:  "0600" }
        -                  { src:   "id_ed25519.pub",
                             mode:  "0644" }
        -                  { src:   "id_rsa",
                             mode:  "0600" }
        -                  { src:   "id_rsa.pub",
                             mode:  "0644" }

    ###########################################################################################
    ##  Add jlowther user account  ############################################################
    ###########################################################################################
    - name:                add jlowther account
      user:
        name:              "jlowther"
        shell:             "/bin/bash"
        password:          "$6$C9aAoxnkWc34euVM$RIEgs4JGVs8622CyADr1qB5N.gYPv789T8KslaVlPJXAwKbSq26NOIYO16TGzz2jUW0zjLhAznxfYde5yxStB."
        #                  generate sha256 hashed password
        #                  python -c "import crypt; print crypt.crypt('joske')"

    - name:                give jlowther sudo root
      copy:
        src:               "/home/jlowther/hadoop/020_jlowther-nopasswd"
        dest:              "/etc/sudoers.d/020_jlowther-nopasswd"
        mode:              "0600"
        owner:             "root"

    - name:                Make sure ~jlowther/.ssh exists
      file:
        name:              "/home/jlowther/.ssh"
        mode:              "0700"
        owner:             "jlowther"
        group:             "jlowther"
        state:             "directory"

    - name:                jlowther's ssh keys
      copy:
        src:               "/home/jlowther/.ssh/{{ item.src}}"
        dest:              "/home/jlowther/.ssh/"
        mode:              "{{ item.mode }}"
        owner:             "jlowther"
        group:             "jlowther"
      loop:
        -                  { src:   "authorized_keys",
                             mode:  "0600" }
        -                  { src:   "config",
                             mode:  "0600" }
        -                  { src:   "id_ecdsa",
                             mode:  "0600" }
        -                  { src:   "id_ecdsa.pub",
                             mode:  "0644" }
        -                  { src:   "id_ed25519",
                             mode:  "0600" }
        -                  { src:   "id_ed25519.pub",
                             mode:  "0644" }
        -                  { src:   "id_rsa",
                             mode:  "0600" }
        -                  { src:   "id_rsa.pub",
                             mode:  "0644" }

    ###########################################################################################
    ##  Update & Upgrade, removing all wolfram software #######################################
    ###########################################################################################
 
    - name:                Apt update
      apt:
        update_cache:      yes
 
    - name:                Apt upgrade
      apt:
        upgrade:           dist

    ###########################################################################################
    - name:                set locale to en_US.UTF-8
      locale_gen:
        name:              en_US.UTF-8
        state:             present

    - name:                Set timezone to America/Boise
      timezone:
        name:              "America/Boise"
        hwclock:           "UTC"
